### ISSUE TITLE
Unable to do `xtool sdk Xcode.xip`

### ISSUE THREAD

**Issue by TreorTang-sz** [xtool-org/xtool#69]
## Description

I am trying to install it inside WSL with Xcode16.3.xip, but I except this:
```
tang@Tang:~$ xtool sdk   Xcode_16.3 (1).xip

gzip: stdin: unexpected end of file
/usr/bin/tar: Child returned status 1
/usr/bin/tar: Error is not recoverable: exiting now
```
## Environment
I am sure that the `xip` file is integral， since I download it twice.
Please provide as much of the following information as is relevant.

Host OS (macOS/Linux/WSL):WSL 

Host OS version:
WSL2 ubuntu

iOS device version:

Is this related
Swift version:

Swift version 6.1 (swift-6.1-RELEASE)
Target: x86_64-unknown-linux-gnu

SDK version:

Havn't reached here ;(

**Comment by kabiroberai** [comment]
The `/usr/bin/tar` step occurs before we even get to extracting Xcode.xip; it's when we [download](https://github.com/xtool-org/xtool/blob/fbbd8366ca138a0a44ca28242973b109fe3eced6/Sources/XToolSupport/SDKBuilder.swift#L151) the darwin-tools-linux-llvm toolset. Seems like the download isn't working for you. What do you get when you run the following commands?

```
curl -LO https://github.com/xtool-org/darwin-tools-linux-llvm/releases/download/v1.0.1/toolset-x86_64.tar.gz
file toolset-x86_64.tar.gz
```

**Comment by TreorTang-sz** [comment]
It works, so it is still the `Xcode.xip`'s issue?

**Comment by ngominhtrungit** [comment]
I same error, when run 

`xtool new Hello`
Now generating the Darwin SDK.

Please download Xcode from http://developer.apple.com/download/all/?q=Xcode
and enter the path to the downloaded Xcode.xip.

Path to Xcode.xip: D:\\IOS-build\\Xcode.xip
[Downloading toolset] 100%

anyone help pls

**Comment by ngominhtrungit** [comment]
> I same error, when run
> 
> `xtool new Hello` Now generating the Darwin SDK.
> 
> Please download Xcode from http://developer.apple.com/download/all/?q=Xcode and enter the path to the downloaded Xcode.xip.
> 
> Path to Xcode.xip: D:\IOS-build\Xcode.xip [Downloading toolset] 100% Error: No such file or directory
> 
> anyone help pls

update: I have solved it, fix the path containing Xcode.xip to match the Windows standard

**Comment by kabiroberai** [comment]
I wonder whether networking is broken from within xtool in particular. Could you folks try logging in with `xtool auth` and then running `xtool ds identifiers`?

**Comment by wagner-rebello** [comment]
After some reboot now the xtool setup works, feels like my computer toolset download download are to slow to start and this combined with default HTTPClient timeout (Seems like it's 10 seconds) this throws the exception.
Maybe increasing the timeout can help with this issue.
Curl log to show the elapsed time between download start and download end.

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0
100 41.6M  100 41.6M    0     0  1746k      0  0:00:24  0:00:24 --:--:-- 9337k

**Comment by kabiroberai** [comment]
Good suggestion @wagner-rebello, should be fixed once #111 lands

**Comment by Jenfong** [comment]
+ env
os: fedora 42
+ setup toolset
```
tar -xzvf toolset-x86_64.tar.gz
cp -ar bin/*  /bin
```
+ incorrect path
```shell
$ xtool sdk install /home/hunter/xtool/Xcode_16.3.xip 

gzip: stdin: unexpected end of file
/usr/bin/tar: Child returned status 1
/usr/bin/tar: Error is not recoverable: exiting now
Error: HTTPClientError.connectTimeout
```

you shoud correct your path,without  blank it the end of the path
+ correct path but failed
```shell
$ xtool sdk install /home/hunter/xtool/Xcode_16.3.xip
[Downloading toolset] 100%
[Extracting XIP] 71%writing chunk to ./Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/updaters/libAppleTypeCRetimerUpdater.tbd failed: No space left on device

```
with new question 'No space left on device' 
```shell
$ df -lh
tmpfs                  3.1G  2.2M  3.1G    1% /run
tmpfs                  1.0M     0  1.0M    0% /run/credentials/systemd-journald.service
tmpfs                  7.7G  7.7G     0  100% /tmp
/dev/sda5              411G   35G  376G    9% /home
tmpfs                  1.0M     0  1.0M    0% /run/credentials/systemd-resolved.service
tmpfs                  1.6G  388K  1.6G    1% /run/user/1000
tmpfs                  1.6G   72K  1.6G    1% /run/user/0
xtool-x86_64.AppImage   49M   49M     0  100% /tmp/.mount_xtoolmGMkdJ
```
```shell
$ xtool sdk --help
OVERVIEW: Install the Darwin Swift SDK

USAGE: xtool sdk install <path>

ARGUMENTS:
  <path>                  Path to Xcode.xip or Xcode.app

OPTIONS:
  --version               Show the version.
  -h, --help              Show help information.

```

**Comment by gessha** [comment]
I had the same issue as @Jenfong and his last recommendation `sudo mount -o remount,size=15G /tmp` let me finish the sdk installation process. 

Since the process was pretty demanding RAM-wise as well, I had to terminate all other applications and leave only the terminal where the SDK was being installed. 

Note that for some reason `swift sdk list` didn't work the first time and I had to run `xcode sdk $PATH_TO_XCODE.XIP` again before `swift sdk list` registered it properly.

**Comment by Jenfong** [comment]
> I had the same issue as [@Jenfong](https://github.com/Jenfong) and his last recommendation `sudo mount -o remount,size=15G /tmp` let me finish the sdk installation process.
> 
> Since the process was pretty demanding RAM-wise as well, I had to terminate all other applications and leave only the terminal where the SDK was being installed.
> 
> Note that for some reason `swift sdk list` didn't work the first time and I had to run `xcode sdk $PATH_TO_XCODE.XIP` again before `swift sdk list` registered it properly.
env: i5 + RAM 16G + ssd 512G
Actual,I tried many times. I install as follow [xtool.sh doc](https://xtool.sh/documentation/xtool/),
after upgrade swift version,I reinstalled the xcode indeed. swift(6.1 ) + xcode(16.3)  's version shoud be match 
finally I run the demo([xtool create Hello](https://xtool.sh/tutorials/xtool/first-app)) sucess.

**Comment by kabiroberai** [comment]
Meanwhile, the `HTTPClientError.connectTimeout` issue should be resolved as of v1.13.0. Going to close this speculatively, but if anyone encounters the problem again feel free to report it here and I can reopen the issue.

**Comment by CrazyBunQnQ** [comment]
I still encountered the problem

## Environment
Host OS (macOS/Linux/WSL):WSL

Host OS version:
WSL2 ubuntu 24

iOS device version:

Is this related?
Swift version:

Swift version 6.1.2 (swift-6.1.2-RELEASE)
Target: x86_64-unknown-linux-gnu

SDK version:

Havn't reached here ;(

![Image](https://github.com/user-attachments/assets/33830bab-70fb-4e1c-8aca-3fbb4bd9f7a4)
